apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-tunnel
  namespace: default
  labels:
    app: cloudflared-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared-tunnel
  template:
    metadata:
      labels:
        app: cloudflared-tunnel
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --no-autoupdate
        - --url
        - http://polu-birthday-service.default.svc.cluster.local:80
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
