server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Gzip Compression
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1000;

    # Handle HTML routes
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache static assets
    location ~* \.(jpg|jpeg|png|gif|ico|css|js|mp3)$ {
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }

    # Audio range requests support for mobile Safari/Chrome
    location ~* \.mp3$ {
        add_header Accept-Ranges bytes;
    }
}
